### PR TITLE
Update release-process.md

### PR DESCRIPTION
**Pull request by Vatyx**

### CODE REVIEW

**Comment by Vatyx** [comment]
Hmmm, this might not be enough detail.

**Comment by oblm** [comment]
> Hmmm, this might not be enough detail.

Yeah we need to go into more detail. Happy to pair on this if you want?

**Comment by oblm** [comment]
@Vatyx I've blocked out the structure and added the commands that I'm aware of. You still need to:

* Add any specific changes that have to be made to the client prior to building (i.e: do you need to hardcode a local ip?)
* Add steps to run the client.

**Comment by m-samiec** [comment]
Should this have gone into master, or doc-release?

**Comment by Vatyx** [comment]
It should have gone in a while ago but I think master is ok? @oblm

**Comment by oblm** [comment]
`master` is correct for internal documentation as it's not subject to `improbadoc publish`ing.

Side note, I've asked for usage guidelines for `docs-release` here: DOC-1083

**Pull request merged**
