### PR TITLE
GCS-1513 using spectator pawn location

### PR DESCRIPTION
**Pull request by dbsigurd**
#### Description
Changed the GetActorSpatialPostion to use the last sync spectator position if the actor is a player controller and in spectating mode. Otherwise if it is a player controller and not spectating use its focallocation

#### Release note
REQUIRED: Add a release note to the `##Unreleased` section of CHANGELOG.md. You can find guidance for writing useful release notes [here](../SpatialGDK/Extras/internal-documentation/how-to-write-good-release-notes.md). Documentation changes are exempt from this requirement.

#### Tests
I built and deployed this change in a game and verified that I could fly around have things update

STRONGLY SUGGESTED: How can this be verified by QA?
Do a deploy, start spectating and see if the requested position is matching the clients location.

#### Documentation
Updated the comment about the function
#### Primary reviewers
@yumnuska @Vatyx @improbable-valentyn

### CODE REVIEW

**Comment by ernopp** [comment]
@dbsigurd I've added you as a writer in the repo so you can PR directly next time, instead of having to fork first

**Comment by MatthewSandfordImprobable** [comment]
Do we want to merge this?

**Comment by MatthewSandfordImprobable** [comment]
@dbsigurd @improbable-valentyn This looks like it has been reviewed and approved. Can this be merged?

**Comment by dbsigurd** [comment]
Sorry, I thought this had been merged. Looked at the conflict and the files changed quite a bit. I'll close this one and reopen a new one. with the change applied to SpatialActorUtils.h

**Pull request closed without merging**
