### PR TITLE
Default disable session log recording

### PR DESCRIPTION
**Pull request by m-samiec**
#### Description
Session log recording is only available post 15.3.0. Disable by default, and hide from config menu.

#### Primary reviewers
@mironec @improbable-dmitrii

### CODE REVIEW

**Review by improbable-dmitrii — APPROVED** [review]
Do we want to update the pinned runtime version, too?

**Comment by m-samiec** [comment]
> Do we want to update the pinned runtime version, too?

No for now USI etc. are experimental features. When we're ready to remove QBI support fully, we can update the pinned version.

**Review by mironec — APPROVED** [review]

**Comment by mironec** [comment]
CI says "LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module."

**Comment by improbable-dmitrii** [comment]
> > Do we want to update the pinned runtime version, too?
> 
> No for now USI etc. are experimental features. When we're ready to remove QBI support fully, we can update the pinned version.

Is there a version that supports session log recording but does not include USI? Unless we update the pinned version, no one will be able to record session logs even if they enable the config flag.

**Comment by m-samiec** [comment]
> Is there a version that supports session log recording but does not include USI? Unless we update the pinned version, no one will be able to record session logs even if they enable the config flag.

Yes any official version post 15.3 will support session log recording. And if you can record session logs if you set a custom bundle locally.

**Pull request merged**
