### PR TITLE
Feature/unr 1454 config receptionist

### PR DESCRIPTION
**Pull request by sang-tian**
**Contributions**: We are not currently taking public contributions - see our [contributions](CONTRIBUTING.md) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

-------

#### Description
When testing on iOS, the client always needs to connect to another machine which hosts the server but it can't read the receptionistHost argument from CLI. In this case, adding a setting property will enable the local test workflow for mobile platforms.

#### Release note
TODO

#### Tests
Machine A and B are on the same LAN. Start a server on A. In Unreal Editor on B, configure the Default Receptionist Host using A's IP address. Start the client in the editor, and it should be able to connect to A.

#### Documentation
WIP

#### Primary reviewers
@jessicafalk

### CODE REVIEW

**Comment by sang-tian** [comment]
> This looks like a good first step. However it means that you will have to rebuild your worker every time you want to change the runtime ip.
> If you add a new button to start the game on your device and pass in the command line arguments when starting the game, it will you to be more flexible.
> However, you would need to store the runtime ip somewhere else and right now I can't give you a best practice for that. I'm looking into it myself (we only added this functionality for android so far), can tell you more about it next week.

I think the login/connection UI should be implemented in the game project rather than GDK, because different users/games want different in-game workflows in the different development stages. GDK should only provide some basic in-editor test workflows.

**Comment by jessicafalk** [comment]
I disagree with this. After having worked on mobile for over a year, I can tell you that it is very painful to always have to re-build the client whenever the ip address or the dev auth token changes. This is not something that a developer may want to add as UI inside the game.

At the beginning we also thought that adding UI would beenough, but we quickly realized that this increases the maintenance burden. What if you want to test your "production UI" while still developing? You can't do this if you need to use the UI to configure the ip address or dev auth token. If they want to do this, they are able to change their UI and have development & production-ready UI. However, by providing an in-editor flow to quickly restart the application with a different ip-address or dev auth token, you make iteration time so much shorter and the whole flow is easier to use.

**Comment by joshuahuburn** [comment]
Hey sorry I'm late to the party on this one. Discussed with @jessicafalk offline, a 'config' variable is actually saved to disk inside of Unreal's `.ini` files which can be found in your game projects `Config` directory, this means you can change these values without requiring a rebuild. One thing I'd like you to confirm @sang-tian is whether you can access and modify these .ini files from within a packaged iOS build, or change them and simply repackage. This is how it works on windows and so is a convenient workflow :D

**Comment by sang-tian** [comment]
Discussed with @jessicafalk about the in-editor flow and we agreed that we can add the buttons for launching the client on iOS/Android in the next milestone. That's how Unity GDK does and in that way, the developers won't have to re-package every time they change the IP address or dev-auth-token.

**Comment by jessicafalk** [comment]
@sang-tian  check what josh was writing about. Apparently the ini files already take care of that? could you double-check that?

**Comment by sang-tian** [comment]
> @sang-tian check what josh was writing about. Apparently the ini files already take care of that? could you double-check that?

There's no INI file in an IPA package built from UE 4.20. I'll take a look later to see if the INI files are filtered when packaging.

**Pull request merged**
