### PR TITLE
Made generating schema for all supported classes opt out

### PR DESCRIPTION
**Pull request by Vatyx**

### CODE REVIEW

**Comment by girayimprobable** [comment]
Have you tested this with a more complicated piece of codebase? ShooterGame maybe?

**Comment by Vatyx** [comment]
I don't think there's much to test here? There's another task to make sure we load all the correct classes.

**Comment by girayimprobable** [comment]
Didn't we run into some issues with Scavengers when we generated everything? I wanna make sure that's not the case anymore by default.

**Comment by Vatyx** [comment]
The way to fix that for now is to make sure you launch the game once before generating schema. That's why Dave ran into that issue.

**Pull request merged**
