### PR TITLE
Switching to Linux CI

### PR DESCRIPTION
**Pull request by padhansell**
**Contributions**: We are not currently taking public contributions - see our [contributions](CONTRIBUTING.md) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Updates CI to target Linux rather than Windows

### CODE REVIEW

**Comment by Vatyx** [comment]
Do we know this works?

**Comment by padhansell** [comment]
Build succeeded against Linux, but BuildKite annotations need more tidying up as they still talk about building for Windows

**Comment by Vatyx** [comment]
Ok great

**Comment by DoomGerbil** [comment]
@padhansell @Vatyx  See https://github.com/spatialos/UnrealGDK/pull/808

**Comment by Vatyx** [comment]
Closing because of other PR

**Pull request closed without merging**
