### PR TITLE
If schema database is manually deleted, reset internal state for schema generator

### PR DESCRIPTION
**Pull request by Vatyx**
#### Description
If the SchemaDatabase doesn't exist on generation of schema, ClassPathToSchema is emptied to reset what classes are supported.

#### Release note
Bugfix - Deleting the schema database reset the starting component ID

#### Primary reviewers
@m-samiec @BenNaccarato

### CODE REVIEW

**Comment by girayimprobable** [comment]
What's the UNR ticket?

**Comment by girayimprobable** [comment]
Please fill the Description to be more descriptive.

**Comment by Vatyx** [comment]
No ticket. Just did it quickly since it was getting annoying to have to restart my editor. Should I make one?

**Comment by girayimprobable** [comment]
Yep create a ticket please.

**Pull request merged**
