### PR TITLE
🐛 Hierarchy migrations only ever update the SpatialOS position of the root Actor

### PR DESCRIPTION
**Pull request by alastairdglennie**
How doesn't this break everything

### CODE REVIEW

**Review by jacquese — APPROVED** [review]
this is an excellent change

**Comment by alastairdglennie** [comment]
> this is an excellent change

very pog

**Comment by m-samiec** [comment]
Nice - this should go straight into the rc though

**Review by simonsarginson — APPROVED** [review]

**Review by m-samiec — CHANGES_REQUESTED** [review]
This should go in via the rc branch - please don't merge

**Pull request closed without merging**
