### PR TITLE
UNR-214: Updated README.md

### PR DESCRIPTION
**Pull request by danielimprobable**
This PR updates the README.md to reflect the changes to how we build the GDK

Primary reviewer: @ElleEss @joshuahuburn

### CODE REVIEW

**Review by joshuahuburn — COMMENTED** [review]
Couple comments.

**Review by davedolben — COMMENTED** [review]
Looks good, but it would be nice to break down the local build process a little more. There's times when you can skip parts of the process, and there's no mention of running the interop codegen step or doing `spatial worker codegen`.

**Review by ElleEss — COMMENTED** [review]
There's elements I would like to try to phrase more simply, and there's a whole load of comments on here suggesting content. PRs are quite tricky to work with when there's a lot of new text and discussion over content.
Wondering if it might be better to get the bulk of this discussed and agreed in a GDoc first?

**Review by ElleEss — COMMENTED** [review]
Popped this (and all the comments) into a GDoc to help us make it all lovely: https://docs.google.com/document/d/1Ufnso5WiUIxB2lOW6U8BtqQpO9vleXKX94Z4tPTJ928/edit

**Pull request closed without merging**
