### PR TITLE
Default to 4.24 engine

### PR DESCRIPTION
**Pull request by m-samiec**
#### Description
Some of our CI pipeline uses the first entry in unreal-engine.version, switched it to our latest version, 424.

#### Release note
Not needed - Internal ci change

#### Primary reviewers
@mironec

### CODE REVIEW

**Comment by mironec** [comment]
Kicked off an example project build: https://buildkite.com/improbable/unrealgdkexampleproject-nightly/builds/740

**Comment by mironec** [comment]
Oh, I remember now, probably want to merge feature/4.24-support into example project master, had to change some blueprint nodes.

**Comment by mironec** [comment]
https://github.com/spatialos/UnrealGDKExampleProject/pull/122/files
But not sure if we want to do it now, as it will break example project on 4.23

**Comment by m-samiec** [comment]
CI passed - https://buildkite.com/improbable/unrealgdkexampleproject-nightly/builds/763

**Pull request merged**
