### PR TITLE
UNR-435 merge plugins

### PR DESCRIPTION
**Pull request by mpmisko**
#### Description

We currently have two separate plugins which means a lot of duplicate code. This PR merges these plugins into one. We keep the `SpatialGDKEditorToolbar` plugin and merge the `SpatialOSEditorToolbar` into it.

#### Tests

I have run the unreal editor and all the functionality works as previously.

#### Documentation

Jira link: https://improbableio.atlassian.net/browse/UNR-435

#### Primary reviewers
@danielimprobable @m-samiec

### CODE REVIEW

**Review by danielimprobable — COMMENTED** [review]
Could you create a Jira for the issue you found when launching both codegen and spatial at the same time?

**Review by danielimprobable — APPROVED** [review]
LGTM just a minor comment

**Review by joshuahuburn — COMMENTED** [review]
Lookin good, couple questions.

**Review by joshuahuburn — COMMENTED** [review]
Couple comments 💃

**Review by m-samiec — APPROVED** [review]
One comment - otherwise LGTM! Great work, this is very overdue change.

**Review by joshuahuburn — APPROVED** [review]
LGTM

**Pull request merged**
