### PR TITLE
Default enable SpatialView

### PR DESCRIPTION
**Pull request by samiwh**
#### Description
Default enable spatial view

### CODE REVIEW

**Review by mironec — APPROVED** [review]
I am scared

**Comment by mironec** [comment]
Also, is the setting exposed in the spatialos settings? I think I would prefer it exposed for the first release + the release note Mike mentioned.

**Comment by samiwh** [comment]
Making the option exposed makes sense. Also makes the release note easier to write as it's not a pure internal feature then.
Will do

**Review by jacquese — APPROVED** [review]
nice

**Review by jessicafalk — APPROVED** [review]

**Pull request merged**
