### PR TITLE
UNR-207: fix RepNotify for struct properties

### PR DESCRIPTION
**Pull request by davedolben**
* Check if the root property in a MultiClient update has RepNotify set on it
* De-dup RepNotify updates so that they don't get triggered multiple times for a single struct property

Paired with: https://github.com/improbable/unreal-gdk-sample-game/pull/17

### CODE REVIEW

**Review by m-samiec — COMMENTED** [review]
How about switching RepNotifies type to a TSet, and just grabbing the TArray when it gets passed into PostReceiveSpatialUpdate? Then we'd only need one container, and wouldn't need to do the 'contains' checks as sets are already unique.

**Review by m-samiec — APPROVED** [review]
LGTM

**Review by danielimprobable — APPROVED** [review]
LGTM

**Review by joshuahuburn — APPROVED** [review]
LGTM

**Pull request merged**
