### PR TITLE
Bugfix/unr 3992 replicating actors with nonreplicating owners

### PR DESCRIPTION
**Pull request by cmsmithio**
#### Description
We only want to AddOwnerInterestOnServer if the owner is replicating, otherwise we get the warning "Interest for Actor <ActorName> is out of date because owner <OwnerName> does not have an entity id."

#### Release note
Release note added.

#### Tests
Verified the warning no longer fires on our project.

#### Documentation
Release note.

#### Primary reviewers
@m-samiec @ImprobableNic

### CODE REVIEW

**Comment by ImprobableNic** [comment]
I actually should do a followup to check what happens with load balancing in general since we follow the Owner in hierarchies.

**Comment by m-samiec** [comment]
@cmsmithio this has gone into master, will you merge it locally or should we preport this to the rc?

**Comment by cmsmithio** [comment]
@m-samiec We have it merged locally.  I can pull it into the rc as well if you like.

**Comment by ImprobableNic** [comment]
I have the other PR to preport as well, I'll add this one.

**Pull request merged**
