### PR TITLE
Remove EditorWorkerController

### PR DESCRIPTION
**Pull request by jessicafalk**
#### Description
Removed the EditorWorkerController, because we don't seem to need it anymore. Ran multiple PIE sessions and new workers were able to gain authority without problems

#### Release note
done

#### Tests
the EditorWorkerController was supposed to enable you to restart PIE sessions in an 8 second window when using the compatibility mode for the runtime. This will still work without the controller. Ensure you are using the compatibility mode for the runtime. Start a PIE session, stop it and restart it in an 8 second window. The workers spawned should be able to connect and become authoritative.

#### Documentation
no documentation needed.

#### Reminders (IMPORTANT)
If your change relies on a breaking engine change:
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in `SpatialGDK\Source\SpatialGDK\Public\Utils\EngineVersionCheck.h`. This helps others by providing a more helpful message during compilation to make sure the GDK and the Engine are up to date.

If your change updates `Setup.bat`, `Setup.sh`, core SDK version, any C# tools in `SpatialGDK\Build\Programs\Improbable.Unreal.Scripts`, or hand-written schema in `SpatialGDK\Extras\schema`:
* Increment the number in `RequireSetup`. This will automatically run `Setup.bat` or `Setup.sh` when the GDK is next pulled.

no changes needed

#### Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention them.
@joshuahuburn @m-samiec

### CODE REVIEW

**Comment by improbable-valentyn** [comment]
It looks like you only removed the `.cpp` and not the header?

**Comment by jessicafalk** [comment]
ah yes, I removed the header in the visual studio solution but forgot to properly remove it as well 🤦

**Comment by m-samiec** [comment]
Did you test in both runtimes?

**Comment by jessicafalk** [comment]
yes, I tested it in both runtimes.

**Pull request merged**
