### PR TITLE
Fix race condition in Spatial Test framework that would cause tests t…

### PR DESCRIPTION
**Pull request by cmsmithio**
…o time out with one or more workers not ready to begin the test.

#### Description
Fixed race condition in Spatial Test framework that would cause tests to time out with one or more workers not ready to begin the test.  If OwningTest was received/processed via replication after bReadyToRegisterWithTest, the flow controller would never get registered.

#### Release note
Release note added.

#### Tests
Verified on our project that Spatial tests no longer timeout with the warning:
"...the number of connected clients/server is less than the number of required clients..."

STRONGLY SUGGESTED: How can this be verified by QA?

#### Documentation
Release note

#### Reminders (IMPORTANT)
If your change relies on a breaking engine change:
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in `SpatialGDK\Source\SpatialGDK\Public\Utils\EngineVersionCheck.h`. This helps others by providing a more helpful message during compilation to make sure the GDK and the Engine are up to date.

If your change updates `Setup.bat`, `Setup.sh`, core SDK version, any C# tools in `SpatialGDK\Build\Programs\Improbable.Unreal.Scripts`, or hand-written schema in `SpatialGDK\Extras\schema`:
* Increment the number in `RequireSetup`. This will automatically run `Setup.bat` or `Setup.sh` when the GDK is next pulled.

#### Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention them.

### CODE REVIEW

**Review by mironec — APPROVED** [review]
Approving, but can't visuallize exactly how this failed.
We also have this hack in the flow controllers:
```
void ASpatialFunctionalTestFlowController::BeginPlay()
{
	Super::BeginPlay();

	if (HasAuthority())
	{
		// Super hack
		FTimerHandle Handle;
		GetWorldTimerManager().SetTimer(
			Handle,
			[this]() {
				bReadyToRegisterWithTest = true;
				OnReadyToRegisterWithTest();
			},
			1.0f, false);
	}
}
``` I think this *could* help with that, but not completely sure.

**Comment by cmsmithio** [comment]
> Approving, but can't visuallize exactly how this failed.
> We also have this hack in the flow controllers:
> 
> ```
> void ASpatialFunctionalTestFlowController::BeginPlay()
> {
> 	Super::BeginPlay();
> 
> 	if (HasAuthority())
> 	{
> 		// Super hack
> 		FTimerHandle Handle;
> 		GetWorldTimerManager().SetTimer(
> 			Handle,
> 			[this]() {
> 				bReadyToRegisterWithTest = true;
> 				OnReadyToRegisterWithTest();
> 			},
> 			1.0f, false);
> 	}
> }
> ```
> 
> I think this _could_ help with that, but not completely sure.

Hi Miron, if you look at the implementation of this function:

```
void ASpatialFunctionalTestFlowController::OnReadyToRegisterWithTest()
{
	if (!bReadyToRegisterWithTest || OwningTest == nullptr)
	{
		return;
	}

	OwningTest->RegisterFlowController(this);

	if (OwningTest->HasPreparedTest())
	{
		SetReadyToRunTest(true);
	}
}
```

In the failure case, this function early-outs b/c OwningTest is nullptr.  There is no other codepath that will attempt to register the flow controller or call SetReadyToRunTest(true), so the server never gets notified that this flow controller is ready.  The server eventually times out, resulting in test failure.

**Comment by mironec** [comment]
Ah yes, I meant that your fix *could* make the hack obsolete.

**Comment by mironec** [comment]
But I haven't tested - will do so, once this is in.

**Pull request merged**
