### PR TITLE
Update build script to use SimulatedPlayer instead of FakeClient

### PR DESCRIPTION
**Pull request by WVerlaek**
#### Description
We are renaming "fake client" to "simulated player" to align terminology across (upcoming) projects.

The build script has the option to build headless Linux (fake) clients. This PR renames the option to build these headless Linux clients from FakeClient to SimulatedPlayer.

For backwards compatibility the build script will still support FakeClient as a GameName (which results in `UnrealFakeClient@Linux.zip` as the created assembly), but will show a warning to use SimulatedPlayer instead. Using SimulatedPlayer as the GameName will result in the same assembly being created under a different name: `UnrealSimulatedPlayer@Linux.zip`. 

#### Release note
No release notes: the FakeClient/SimulatedPlayer option in the build script is currently for internal use only.

#### Tests
Tested this change by building both a FakeClient and SimulatedPlayer assembly for an existing project. Result when using FakeClient hasn't changed, except for now showing a warning message. Using SimulatedPlayer outputs the same assembly as FakeClient under a different name.

### CODE REVIEW

**Comment by Vatyx** [comment]
Is backwards compatibility really needed? I don;t think fake players are being that extensively used.

**Comment by WVerlaek** [comment]
Just an error when specifying FakeClient would be fine as well, but I think we should at least make it clear that FakeClient is no longer supported if you're trying to build using FakeClient. Without that, building a FakeClient will use the fall-through build option, and it won't be obvious that it did not build the expected assembly. We can remove the error/warning for FakeClient in a following release

**Comment by Vatyx** [comment]
Yeah I guess lets make it an error.

**Comment by WVerlaek** [comment]
Incremented the RequireSetup number as well, the changes to the Build script will need to be rebuilt after pulling

**Pull request merged**
