### PR TITLE
NOT_TO_BE_MERGED_BUT_REVIEW_REQUESTED: DOC-1337 and page improvements

### PR DESCRIPTION
**Pull request by jostichbury**
Changes to the "How to use schema" page to introduce the CookAndGenerateSchema commandlet and make some improvements to the clarity of the text in general

**Contributions**: We are not currently taking public contributions - see our [contributions](CONTRIBUTING.md) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

DOCUMENTATION TICKET

Description
Address the ticket DOC-1337 by adding content to introduce CookAndGenerateSchema commandlet and make general page improvements while on the page

Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @anne-edwards @mattyoung-improbable

### CODE REVIEW

**Comment by jostichbury** [comment]
Please stand by for a link to the page on staging to simplify the review process...

**Comment by jostichbury** [comment]
Right, the page changes are now visible on staging here: https://docs-staging.improbable.io/unreal/alpha/content/how-to-use-schema

The changes will NOT go onto `docs-preview` but I'm presenting them here so it's easy for @ernopp to review. When the readme portal is open for business, they'll go on there.

Please could I have your thoughts, dear reviewers (@ernopp, @anne-edwards ), and I'll get this ticket complete. 

One question for Ernie:

Will the cooking commandlet eventually replace the command line method (such that we should remove the documentation about it)? At present, I have a section that reads as follows. Is it OK?


```
Generate schema during the cooking process#
The CookAndGenerateSchemaCommandlet command generates the schema needed by your game, and does so during the cooking process, so it is like running the full scan described above, but is faster. It will ultimately replace the command line schema generation described above, but is currently experimental and in ‘alpha’ state.
```
Is this OK?

**Comment by ernopp** [comment]
@jostichbury thanks for this. 
the content looks good - only thing I was wondering is why we are adding (duplicating?) the "how-to-use-schema" doc in the spatialos concepts?  I think we should keep the SpatialOS concepts explanation focused as it is now: https://docs.improbable.io/unreal/alpha/content/spatialos-concepts/schema-and-snapshots

**Comment by jostichbury** [comment]
Thanks Ernie. I'm not sure I follow, as I cannot find this level of information about building the schema elsewhere (but I'm not that familiar with all the docs and may have missed it). I have @ElleEss on the reviewer list now, so we can discuss within the TW team and decide.

**Comment by jostichbury** [comment]
Now on readme

**Pull request closed without merging**
