### PR TITLE
Schema Database: add lexicographical sort by Key (path name) when saving uasset

### PR DESCRIPTION
**Pull request by DW-Sebastien**
#### Description
Sort the entries in the SchemaDatabase before saving it, using Unreal FString's lexicographical operator<, so now we can open the uasset in Editor and actually browse efficiently through it.

#### Release note
Sort the entries in the SchemaDatabase to help reading it in Editor.

#### Tests
Open SchemaDatabase.uasset in Editor to see that "Actor Class Path to Schema" is now sorted by Path, as well as "Subobject Class Path to Schema", as "Level Path to Component Id"

### CODE REVIEW

**Comment by MatthewSandfordImprobable** [comment]
@mattyoung-improbable If you like, let's get this in?

**Comment by MatthewSandfordImprobable** [comment]
@DW-Sebastien would you mind merging master back into your branch and then we can get into the main repo.

**Comment by SRombauts** [comment]
Ta-da! Here you are :)

**Comment by MatthewSandfordImprobable** [comment]
Master update before I saw this noooooooo!
Sorry but would you update again and hit the squash and merge?

**Comment by SRombauts** [comment]
Hello, @MatthewSandfordImprobable I merged it again, but I won't be allowed to merge it myself since I don't have write access!

**Comment by DW-Sebastien** [comment]
Sorry, I have been messing with multiple Github accounts ;)

**Comment by MatthewSandfordImprobable** [comment]
Released the build test will never finish. Creating our own internal PR that we will merge. Sorry for the mistake Sebastian.

**Pull request closed without merging**
